### ISSUE TITLE
Forecast is not working correct.

### ISSUE THREAD

**Issue by 00107** [VladimirV01/t5_informer#1]
The weather forecast from Openweathermap is not working correctly. Day1 is correct, Day2 has incorrect values and Day3 provides no values. I've had this behavior for a few weeks, but I can't find a solution myself. Openweathermap itself provides correct prediction values and the API works. 
Any ideas?
![IMG_1653](https://github.com/VladimirV01/t5_informer/assets/5302895/496005c5-201a-4d06-acb5-380085fe6bb9)

**Comment by VladimirV01** [comment]
Hello @00107,

Please help me understand correctly the issue.
Was it ever working for you and suddenly stopped or you are only starting to configure it now?

Could you also share the homeasssitant configuration.yaml file part which covers the sensor that aggregates the forecast data?

**Comment by 00107** [comment]
Hello @VladimirV01 
thanks for the quick response!
Yes, at the beginning it worked perfectly for several weeks. Suddenly the forecast values ​​for the third day were missing. Upon closer inspection I noticed that even for day 2 the values ​​did not match those shown by Openweathermap for this location. Day1 values are ok. 
That's strange, isn't it?

This is my yaml of the sensor: https://wastebin.diefe.de/-3xY5a.yaml

<img width="1001" alt="Bildschirmfoto 2024-06-23 um 10 49 42" src="https://github.com/VladimirV01/t5_informer/assets/5302895/07001a1b-c35d-4506-bf69-176277bd6578">

**Comment by VladimirV01** [comment]
@00107,

I have checked the sensor and it looks exactly as mine, which is still working as expected. 

Could you please run the service "weather.get_forecasts" from home assistant and share the output? 
I presume the issue is somewhere around the input data.

**Comment by 00107** [comment]
I first had to look at how to run a service... ;-) I hope I did it right. Here is the output:
https://wastebin.diefe.de/7p8Ygc.yaml

**Comment by 00107** [comment]
I have the feeling that it is due to the query type. If I select "hourly" when running the service, the values ​​end after two days. If I select "daily" I get forecast data for the next 7 days.

For testing purposes I set the configuration.yaml to Daily. Now I get values ​​for day 3, but the min/max calculation and condition is no longer correct. --> https://wastebin.diefe.de/YoqZ5c.yaml

 I use API V3.0, could it be related to that?

**Comment by VladimirV01** [comment]
Yes, you are correct. Your hourly forecast contains data for current and two more days, however the informer show the data for the next 3 days. 

On the other hand, you could use the daily forecast built into openwethermap since it is available for you, and there is no need to make all the calculations, as I did. 

If you want to share a sample of daily forecast returned by the service, I can check later today how the sensor could be modified to use your data.

**Comment by 00107** [comment]
> If you want to share a sample of daily forecast returned by the service, I can check later today how the sensor could be modified to use your data.

That would be great, thank you! :) 
Sample data of daily forecast: https://wastebin.diefe.de/3n0IPc.yaml

By the way: Is it somehow possible to display the three letters of the days in German language? (e.g. Tue = Die)

**Comment by 00107** [comment]
@VladimirV01 
I have tried to adapt the code myself in the meantime. It works so far, but I am not sure if everything is correct. Unfortunately, my coding knowledge is not that good...
https://wastebin.diefe.de/0b+5mb.yaml

**Comment by VladimirV01** [comment]
@00107,

Your template looks good!

Unfortunately I can not test it on my setup since the daily forecast is not available for the free version, but it should be working fine.
Does it display the correct information on your device?

**Comment by 00107** [comment]
Yes, the display looks good so far.
Thanks again for your great work and support. I think this issue can be closed. 

![IMG_1653](https://github.com/VladimirV01/t5_informer/assets/5302895/6134a55e-44bc-4621-88e8-65898c00a44c)

**Comment by 00107** [comment]
Yes, the display looks good so far.
Thanks again for your great work and support. I think this issue can be closed. 

![IMG_1654](https://github.com/VladimirV01/t5_informer/assets/5302895/138981ba-3605-4b45-8d4a-412ec4df3822)

**Comment by VladimirV01** [comment]
@00107,

Actually I didn't do much here. 
You solved it by yourself, and I think you should be proud of your work! 

I will also update the home assistant configuration  example file in this repository to cover the case of using the daily forecast!
