### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by balbulator** [VladimirV01/t5_informer#2]
Hello, I want to thank you for the good work. Checking the operation of the weather forecast sensors in HA, I saw errors in the code, namely extra brackets in the forecast attributes
You do:
`day2_condition: "{{ (full_data['weather.openweathermap']['forecast'] | selectattr('datetime', 'search', (now().date() + timedelta(days=2)) | string ) | join(', ', attribute='condition') }}"`
and it should be like this:
`"{{ full_data['weather.openweathermap']['forecast'] | selectattr('datetime', 'search', (now().date() + timedelta(days=2)) | string ) | join(', ', attribute='condition') }}"`
this is seen in multiple attributes (the first parenthesis is redundant)
Sorry for my English

**Comment by VladimirV01** [comment]
Hello @balbulator,

Thank you for pointing it out to me. 
I do agree there are errors and the general configuration example was awful. :) 

Anyway, I took this opportunity and used some AI magic to rewrite the HA configuration example and make it more readable, optimized and efficient.
Please take a look and if you find something else which is wrong, don't hesitate to point it out to me in a new issue!

**Comment by VladimirV01** [comment]
Actually, I was too naïve to believe that the AI "improved" code was actually going to work, so after testing it turned out to be broken.
As a result I reverted to the initial config, just removed the suggested parentheses.
